### ISSUE TITLE
No events?

### ISSUE THREAD

**Issue by acopalipsis** [bringking/react-web-animation#34]
How can I find out about the end of the animation?

[spec](https://w3c.github.io/web-animations/#the-animation-interface) -> [onfinish](https://w3c.github.io/web-animations/#dom-animation-onfinish) -> [oncancel](https://w3c.github.io/web-animations/#dom-animation-oncancel)

**Comment by bringking** [comment]
@acopalipsis This is an obvious addition. I will add this as an enhancement and work on it!

**Comment by bringking** [comment]
This was added in v0.1.0 https://github.com/bringking/react-web-animation/releases/tag/v0.1.0
