### ISSUE TITLE
TypeError: Cannot read property 'playState' of null

### ISSUE THREAD

**Issue by NeXTs** [bringking/react-web-animation#37]
Catched this using example from readme.
Any ideas how to fix this?

deps:
"react": "^15.3.1",
"react-dom": "^15.3.1",
"immutable": "^3.8.1"

**Comment by NeXTs** [comment]
it occurs on line 77 of playable.js
this.state.player is null

**Comment by bringking** [comment]
@NeXTs  fix published to NPM with version 0.1.1
