### ISSUE TITLE
Problem with `dangerouslySetInnerHTML`?

### ISSUE THREAD

**Issue by t47io** [bringking/react-web-animation#47]
Hi, I was glad being able to use `react-web-animations`, cool library!

I found something strange when I have an element with `dangerouslySetInnerHTML` inside `<Animation/>`. Simply, the `dangerouslySetInnerHTML` content is not displayed **before** `onPlay`. Once trigged play, it would be fine.

Also tried all possible `fill` options, got the same behavior.

If I use `<Animation/>` inside a wrapper component, and force `shouldComponentUpdate` of the wrapper, I see that _both before **and** after_ animation the `dangerouslySetInnerHTML` is lost, while _only during_ the animation they are displayed.

Any ideas? Could this be a `react` thing?

**Comment by t47io** [comment]
More specifically, if my wrapper is like:
```jsx
const Wrapper = (props) => <Animation {...props}>{props.children}</Animation>
```
And use it with
```jsx
<Wrapper keyframes={keyframes} timing={timing}>
  <div>
    <p dangerouslySetInnerHTML={{ __html: someHtml }} />
  </div>
</Wrapper>
```
The `<p>` appears empty before and after, but only show `someHtml` during the animation

**Comment by bringking** [comment]
@t47io thanks for letting me know about this, I will take a look and see if I can re-create

**Comment by bringking** [comment]
@t47io can I get a little more context on how your specific implementation looks? I am trying this example here and it seems to work okay - https://github.com/bringking/react-web-animation/blob/bug/set-inner-HTML/example/src/with_inner_html.js

**Comment by SiqiTian-minted** [comment]
@bringking Hi, thanks a lot for testing! I tested with your example too, and it works. I found that the problem is with `preact`, not `react`. As the `dangerouslySetInnerHTML` content disappears when I have this in `webpack.config.js`:

```js
    resolve: {
        alias: {
            react: 'preact-compat',
            'react-dom': 'preact-compat',
        },
    },
```

I use `preact` because of its smaller size. I will create another ticket there. Thanks!

**Comment by SiqiTian-minted** [comment]
can close now

**Comment by bringking** [comment]
@SiqiTian-minted okay good to know. I can do a spike and see if there is something we can do to support `preact-compat` and `inferno-compat`

**Comment by SiqiTian-minted** [comment]
good to know and thanks a lot! curious what does it take to support those?

**Comment by bringking** [comment]
@SiqiTian-minted I don't know yet, haven't dug in, I think it might be related to the way we rely on `refs` to get access to the node... but that is just a hunch
