### ISSUE TITLE
Include web-animation-js polyfill?

### ISSUE THREAD

**Issue by t47io** [bringking/react-web-animation#50]
Just came up an idea: since the support for `web-animation` API is limited, would it be a good idea to ship with the polyfill?

**Polyfill**: https://github.com/web-animations/web-animations-js
**Support**: http://caniuse.com/#search=web-animation
![screen shot 2017-03-22 at 7 37 25 pm](https://cloud.githubusercontent.com/assets/4424215/24229506/00f51dd6-0f37-11e7-8b51-36e578315568.png)

**Comment by bringking** [comment]
@t47io, yeah I state that it is a runtime dependency in the Readme (if you want it to work outside Chrome). I don't really want to bundle the runtime, to give users more flexibility. Thanks for the idea though! I appreciate all the help I can get
