### ISSUE TITLE
Does this support svg?

### ISSUE THREAD

**Issue by matt-erhart** [bringking/react-web-animation#63]

**Comment by bringking** [comment]
@matt-erhart Yes, you can see an example on the demo page here - https://github.com/bringking/react-web-animation/blob/master/demo/src/welcome.js

**Comment by matt-erhart** [comment]
Do you have an example with a group or sequence? The svg wrapper seems to block propagation to the e.g. circle elements in it.

**Comment by bringking** [comment]
@matt-erhart I fixed this in the lastest release! Here is the example showing how to use AnimationGroup with an SVG - https://github.com/bringking/react-web-animation/blob/master/demo/src/svg_group.js
