### ISSUE TITLE
Should it work on mobile web ?

### ISSUE THREAD

**Issue by bennyhan9** [bringking/react-web-animation#70]
When test it on mobile it run ok on android, but when try to run it on ios safari, i get:

TypeError: this.node.animate is not a function. (In 'this.node.animate(this.keyframes, this.timing)', 'this.node.animate' is undefined)
startAnimation — animation.js:63
componentDidMount — animation.js:99
measureLifeCyclePerf — ReactCompositeComponent.js:75
(anonymous function) — ReactCompositeComponent.js:264
notifyAll — CallbackQueue.js:76
close — ReactReconcileTransaction.js:80
closeAll — Transaction.js:206
perform — Transaction.js:153
perform — Transaction.js:140
flushBatchedUpdates — ReactUpdates.js:172
flushBatchedUpdates
closeAll — Transaction.js:206
perform — Transaction.js:153
dispatchEvent — ReactEventListener.js:147
dispatchEvent
https://s3.amazonaws.com/infash-assets-staging/brands_icons/tommy_hilfiger_unpressed.png

**Comment by bringking** [comment]
@bennyhan9 it should.. What version of safari are you running on? Are you loading the Web Animations Polyfill?

**Comment by bringking** [comment]
@bennyhan9, I tested it recently on mobile safari and it work with the polyfill loaded
